from typing import Any

SEMANTIC_TEST_CASES: list[dict[str, Any]] = [
    {
        "name": "daily work implicit",
        "input": "مش رحیم امروز کار کرد",
        "expected_event_type": "WORK_EVENT",
        "expected_entity": "مش رحیم",
        "context_entities": ["مش رحیم"],
    },
    {
        "name": "skilled welding progress",
        "input": "نادری جوشکار ۲۰ متر جوش داد",
        "expected_event_type": "WORK_EVENT",
        "expected_entity": "نادری جوشکار",
        "context_entities": ["نادری جوشکار"],
    },
    {
        "name": "informal million payment typo",
        "input": "۱۰۰ ملیون دادم",
        "expected_event_type": "FINANCIAL_EVENT",
        "expected_entity": None,
        "context_entities": [],
    },
    {
        "name": "settlement financial meaning",
        "input": "تسویه شد",
        "expected_event_type": "FINANCIAL_EVENT",
        "expected_entity": None,
        "context_entities": [],
    },
    {
        "name": "known client settlement",
        "input": "کارفرما گفت تسویه شد",
        "expected_event_type": "FINANCIAL_EVENT",
        "expected_entity": "میثم کبیری",
        "context_entities": ["میثم کبیری"],
    },
    {
        "name": "vendor purchase informal spacing",
        "input": "از هادی پور سیم ۵ میلیون خرید کردم",
        "expected_event_type": "FINANCIAL_EVENT",
        "expected_action": "PURCHASE_PAID",
        "expected_entity": "هادی پور",
        "context_entities": ["هادی پور"],
    },
    {
        "name": "material purchase without money is note",
        "input": "۲۰ متر سیم خریدم",
        "expected_event_type": "NOTE_EVENT",
        "expected_action": "NOTE",
        "expected_entity": None,
        "context_entities": [],
    },
    {
        "name": "unpaid purchase creates debt",
        "input": "۵ میلیون خرید کردم ولی پولش را هنوز ندادم",
        "expected_event_type": "FINANCIAL_EVENT",
        "expected_action": "DEBT_CREATED",
        "expected_entity": None,
        "context_entities": [],
    },
    {
        "name": "purchase by dated check",
        "input": "۵۰ میلیون سرامیک خریدم برای ۱۴ مهر ۱۴۰۵ چک دادم",
        "expected_event_type": "FINANCIAL_EVENT",
        "expected_action": "CHECK_PAYMENT",
        "expected_entity": None,
        "context_entities": [],
    },
    {
        "name": "client setup",
        "input": "کارفرما میثم کبیری است",
        "expected_event_type": "SETUP_EVENT",
        "expected_entity": None,
        "context_entities": [],
    },
    {
        "name": "multi worker setup declaration",
        "input": "مش رحیم و آقای صابری به عنوان کارگر ساده در پروژه کار می‌کنند",
        "expected_event_type": "SETUP_EVENT",
        "expected_action": "SETUP",
        "expected_entity": None,
        "context_entities": [],
    },
    {
        "name": "ambiguous reminder remains note",
        "input": "یادم باشد بعدا بررسی کنم",
        "expected_event_type": "NOTE_EVENT",
        "expected_entity": None,
        "context_entities": [],
    },
    {
        "name": "known entity today context blocked from note",
        "input": "رحیم امروز",
        "expected_event_type": "WORK_EVENT",
        "expected_entity": "مش رحیم",
        "context_entities": ["مش رحیم"],
    },
]
